### ISSUE TITLE
如果再次执行的话，应该会出现“重复预约”

### ISSUE THREAD

**Issue by c77180** [liyifeng1994/ssm#11]
这个真的没有出现，我这边测试了下，Junit4会报错的，初学者折腾了下，发现这个问题但是还没有找到解决办法。希望能修改下。 刚才看到更新里面说的“修改预约业务代码，失败时抛异常，成功时才返回结果”，希望文档也及时修改下。

**Comment by liyifeng1994** [comment]
同步修改了哦
