### ISSUE TITLE
导入有异常

### ISSUE THREAD

**Issue by zhangxingong** [liyifeng1994/ssm#12]
Description	Resource	Path	Location	Type
Cannot change version of project facet Dynamic Web Module to 3.1.	ssm		line 1	Maven Java EE Configuration Problem

**Comment by Tuyuda** [comment]
Java版本配置不一样吧。

**Comment by Tuyuda** [comment]
Java版本配置不一样吧。

**Comment by liyifeng1994** [comment]
看下这个issues
https://github.com/liyifeng1994/ssm/issues/21
