### ISSUE TITLE
Controller  url:/模块/资源/{id}/细分 /seckill/list   求具体说明

### ISSUE THREAD

**Issue by addonepiece** [liyifeng1994/ssm#15]
服务可以成功启动。 数据库可以成功链接。 junit test 没问题。现在想进一步做  Controller 的调试。但是不知怎么输入url才能跑到对应  Controller 中的方法。debug时跑不到Controller  里面。求  url:/模块/资源/{id}/细分 /seckill/list   参数的具体说明    在你的这个项目中分别是什么  在哪里设置 什么的 。求详细解释  谢谢！！

**Comment by addonepiece** [comment]
已经搞定了

**Comment by prom1seU** [comment]
老哥怎么搞定的，，我的还是报404
