### ISSUE TITLE
修改预约业务代码，失败时抛异常，成功时才返回结果，控制层根据捕获的异常返回相应信息给客户端，而不是业务层直接返回错误结果。

### ISSUE THREAD

**Issue by Xanthuim** [liyifeng1994/ssm#18]
感觉抛出异常需要额外写很多的异常类吧。这样的好处是什么呢？为什么一定要定义异常类？

**Comment by hylxsfh** [comment]
我的理解是如果不用异常那就要用返回值（0，-1，-2，-3之类），这是面向过程式语言中的方式，面向对象式语言一般都用异常，而且异常可以携带更多的信息。

**Comment by liyifeng1994** [comment]
虽然会定义很多异常类，但是不同业务之间也是可以复用的。如果失败的返回值是false表示不了具体的失败原因。
