### ISSUE TITLE
Basically,but also very detailed!

### ISSUE THREAD

**Issue by Assassin-Antractic** [liyifeng1994/ssm#23]
It's detailed,But it can be more simple when you configure XML.
The number of XML configuration can be less if simple,some of them can configured together.
it will be reasonable when you do it!

**Comment by liyifeng1994** [comment]
For beginner, it's more understandable to write separately for the XML configuration.
If you perfer to use less or no XML configuration, you can see this branch.
https://github.com/liyifeng1994/ssm/tree/no-xml

**Comment by xujinhui2015** [comment]
very good
