### ISSUE TITLE
bookcontroller文件报错

### ISSUE THREAD

**Issue by shenwenkai** [liyifeng1994/ssm#27]
return new Result<>(false, "学号不能为空");

**Comment by OrderSaber** [comment]
导入jsp-api包  将if (studentId == null || studentId.equals("")) {
			return new Result<>(false, "学号不能为空");
		}
改为  if (studentId == null || studentId.equals("")) {
		return new Result<AppointExecution>(false, "学号不能为空");
		}

**Comment by OrderSaber** [comment]
“<AppointExecution>”

**Comment by OrderSaber** [comment]
被屏蔽了发不上去 你在中间填上AppointExecution

**Comment by liyifeng1994** [comment]
可能是你的JDK是8以下
