### ISSUE TITLE
运行环境的要求

### ISSUE THREAD

**Issue by gxhubert** [liyifeng1994/ssm#9]
我本地的环境是 jdk 1.8 Tomacat 8.5 运行的时候老是报错，提示初始化失败。 所以想向你请教一下 你的本地环境是怎样的？

**Comment by liyifeng1994** [comment]
和你一样的

**Comment by summer19940609** [comment]
我在两个机器上都一个项目，UserDaoTest一个能通过一个报错，也是jdk1.8

**Comment by ica10888** [comment]
jdk1.8要用tomcat9.0，要对应版本。
